spring:
  datasource:
    url: jdbc:mysql://${dl_mysql_host:localhost}:${dl_mysql_port:3306}/${dl_mysql_dbname:myneboot}?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
    username: ${dl_mysql_username:root}
    password: ${dl_mysql_password:root}
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      username: ${mongo_username:sioeye}
      password: ${mongo_passwd:sioeye}
      host: ${mongo_host:127.0.0.1}
      port: ${mongo_port:27017}
      database: ${mongo_db:admin}
      authentication-database: ${auth_db:admin}